version: "3.5"

services:
  api01: &api
    image: brenomoura/polinho:v1
    hostname: api01
    environment:
      - DB_URL=postgresql://admin:123@db:5432/rinha
      - MAX_CONN=10

    ports:
      - "8081:3000"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "185MB"

  api02:
    <<: *api 
    hostname: api02
    environment:
      - DB_URL=postgresql://admin:123@db:5432/rinha
      - MAX_CONN=200

    ports:
      - "8082:3000"
 
  nginx:
    image: nginx:1.24.0
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"

  db:
    image: postgres:16.1
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/script.sql
      - ./config/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "160MB"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d rinha'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
