version: "3.5"

services:
  api01: &api
    image: polinho:v1
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - DB_USER=admin
      - DB_PASSWORD=123
      - DB_NAME=rinha

    ports:
      - "8081:3000"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "250MB"

  api02:
    <<: *api 
    hostname: api02
    ports:
      - "8082:3000"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "10MB"

  db:
    image: postgres:16.1
    command: 'postgres -c max_connections=30'
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "290MB"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d rinha'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
